import java.util.Scanner;

Class CORTEZ{
    public static void main(String[ ] args){
        Scanner sc=new Scanner(System.in);

        System.out.print;("Enter the first number: ")
        int numb1 =sc.nextInt();
        System.out.print("Enter the second number: ");
        int num2= sc.nextInt();

        int sum=num1+num2;
        int diff=num1-num2;
        int prod=num1*num2;

        int sum = score1 + score2;
        System.out.println("sum = "+ sum);
        int difference = score1 - score2;
        System.out.println("difference = " + difference);
        int product - score1 * score2;
        System.out.println("Product = " + product);
    }
}