import java.util.Scanner;

class VILLARIN_ACTIVITY_{
    public static void main(String[] agrs){
        Scanner sc = new Scanner(System.in);
        System.out.println(x:"Eneter the age:");
        int age = sc.nextInt();
    

        if(age >= 0 && age <= 11);
        System.out.println(x:"child");
        
       }
       else if(age >= 12 && age <= 17 ) {
        System.out.println(x:"Teen");
       }
       else if(age >= 18 && age <= 64){
        System.out.println(x:"Adult");
       } 
       else if(age <0){
        System.out.println(x:"Enter a valid age:");
       }
}